# Generated by Django 3.2.6 on 2021-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('ItemCat', models.CharField(max_length=15)),
                ('ItemImage', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
