# Generated by Django 3.2.6 on 2021-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoamiRasoiApp', '0002_food_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ItemDesc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
